### ISSUE TITLE
[branch] period-timers - For period timers (instead of trace) on every screen

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#137]
Deploy as a dev version.

**Comment by arouinfar** [comment]
I made this change request for upcoming interviews. Currently the Period Timer is only available on the lab screen, while the Period Trace is available on the other two screens. The goal of this design discussion was to facilitate qualitative discussion around the  period, introduce the concept as one complete oscillation, and to potentially help students use the stopwatch to measure the period.

I've been reviewing some earlier interview footage from last year. Students didn't spend much time engaging with the Period Trace on the first screen (other than to turn it on and off). One student completely overlooked the Period Timer on the last screen (thinking it was still the Period Trace), and had to be prompted at the end of the interview to try it out.  In general, the numeric feedback of the Period Timer helped students engage in the kinds of self-driven inquiry we like to see (e.g. "What happens to the period when I double the length?"), so I'd like to see what happens if the Period Timer appears on all screens.

**Comment by arouinfar** [comment]
@jonathanolson Ideally, I'd like to schedule interviews for this upcoming and Monday & Tuesday. I'll be interviewing on Mac/Chrome which is generally quite stable.

**Comment by jonathanolson** [comment]
See http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.9/pendulum-lab_en.html (has fixes I've done to date).

Please reassign to me once you're done with it (we like to keep "branch" issues open while it's branched in the code). Let me know if I should publish another version of this after applying more fixes.

**Comment by arouinfar** [comment]
Thanks @jonathanolson! Everything seems to be working pretty well on my end, so I don't think there's a need to publish another version. I'll reassign this issue to you after interviews wrap up next week.

**Comment by arouinfar** [comment]
It looks like we will need to make a few tweaks (I will be creating the issues shortly), and do another round of interviews. I will leave this issue open for now.

**Comment by jonathanolson** [comment]
@arouinfar, any verdict on these changes?

**Comment by arouinfar** [comment]
@jonathanolson I'll review the interview notes and get back to you.

**Comment by arouinfar** [comment]
@jonathanolson when I reviewed the early interviews, I think the real issue was with student recruitment. Some had recently learned about harmonic motion in class, and were on a fact-finding mission rather than engaging in exploration. Later interviews (with a different population) had a better flow. I don't think it's necessary to have the Period Timer on all screens, so closing.

**Comment by jonathanolson** [comment]
Deleted the branch, thanks!
