### ISSUE TITLE
Pendulum Alignment Issues

### ISSUE THREAD

**Issue by veillette** [phetsims/pendulum-lab#156]
From a conversation with @phet-steele on Skype
- The left panels must be left aligned and share the same widths.
- The right panels must be right aligned and share the same width.
- For the upper right panel, the titles should be right aligned
- also for the lower left panel, the titles (gravity and friction) should be aligned.

**Comment by jonathanolson** [comment]
Refactoring for left side would be particularly ugly without changes described in https://github.com/phetsims/sun/issues/276, I'll be waiting on that.

**Comment by jonathanolson** [comment]
Left-side alignment complete.

**Comment by jonathanolson** [comment]
I believe the alignment is as described in the pixel-polishing issue. @phet-steele, can you check over the alignment in http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.13/pendulum-lab_en.html?

**Comment by phet-steele** [comment]
👍 , thanks @jonathanolson. However, both vectors are labeled as "Velocity" on the lab screen. Can you fix this so I can more accurately check alignment of the left side, since Acceleration is a longer string?

<img width="257" alt="screen shot 2017-07-18 at 10 06 14 am" src="https://user-images.githubusercontent.com/5863899/28327527-ec5495b6-6ba0-11e7-8a54-746a44d405fe.png">

**Comment by jonathanolson** [comment]
Fixed the string issue, sorry about that!
