### ISSUE TITLE
Use stop button instead of Return

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#173]
In Masses and Springs, we opted for a iconic stop button instead of "Return" (which is not always clear before the first use). Should we do the same in Pendulum Lab? The proximity to the pendulum could also be improved. 

Here are a few options. I have a slight preference for the 2nd option.
![image](https://user-images.githubusercontent.com/8419308/28646747-7f8d688c-7220-11e7-838b-e2987b1aa01f.png)
![image](https://user-images.githubusercontent.com/8419308/28646755-88f39798-7220-11e7-90fe-4f3455d37708.png)

What do you think @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar had to chew on this a bit. I generally like the idea of moving to the "stop" button. However, I think it will be odd to have it where you have placed it (since the string will be able to cross over the button. 

I played around with a few layouts, and the following seemed OK. I feel like the stop sign is in a good place (decent proximity, and pressing the button brings the masses in-line with the button). I felt like the scene selection in this case might be OK near the bottom left control panel since these check boxes are also affecting the nature of the scene.

see what you think 
![28646755-88f39798-7220-11e7-90fe-4f3455d37708](https://user-images.githubusercontent.com/4051174/28733518-c522ad1a-7399-11e7-96fe-ca3833ea3db7.png)

**Comment by arouinfar** [comment]
> I think it will be odd to have it where you have placed it (since the string will be able to cross over the button.

Great point @ariel-phet. I had given the string some thought, but I think I was stuck in the mindset of "keep it at the top like MAS". I really like centering the stop button beneath the pendulum. I've played around a little with the layout and come up with three options. In descending order of my personal preference:

1. Center the pause/step/playback controls in the space between the pendulum string and the panels, move the scene selection buttons an equal amount to the left, so that the stop button is centered between the 2-pendulum and pause buttons.
![image](https://user-images.githubusercontent.com/8419308/28792595-5e9a26d0-75ed-11e7-9124-b89c407f3bb0.png)

2. Center the  pause/step/playback controls in the space between the pendulum string and the panels, but group scene selection buttons together near the tool panel.
![image](https://user-images.githubusercontent.com/8419308/28792623-78445736-75ed-11e7-8308-7db55e1a46d6.png)

3. Group the scene selection buttons together near the tool panel, and move the pause/step/playback controls to the right so that the stop button is centered between the 2-pendulum and pause buttons.
![image](https://user-images.githubusercontent.com/8419308/28792718-c55b2806-75ed-11e7-9a71-2a16a06e82c3.png)

Can you take a look @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar, especially with everything opened, which I had not really thought about, I think option 1 looks the best.

**Comment by arouinfar** [comment]
Thanks @ariel-phet! I really like the balance of option (1).

@jonathanolson we've decided to replace the Return button with a stop button, as mocked up in option (1) of https://github.com/phetsims/pendulum-lab/issues/173#issuecomment-319159805. The stop button is also being used in Masses and Springs, and I believe the icon was drawn in code there.

**Comment by jonathanolson** [comment]
Implemented, are any changes needed?

**Comment by arouinfar** [comment]
Looks great @jonathanolson! The Period Timer doesn't reset if stopped mid-recording, but I'll open a separate issue for that (behavior predates the Restart > Stop change).
