### ISSUE TITLE
Gravity slider step size

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/pendulum-lab#183]
@jonathanolson - Can you change the jumps on the gravity slider to be every 1 or 0.5 m/s2. Right now it is harder to do experiments of doubling because it requires using the tweakers. The drop down allows you to easily return to earth at any time, so I think it is OK to make custom have more of an easy slider/tweaker use combination. If 0.5 allows easy reproducible hitting of each value that would work OK. Otherwise drop it to jumps of 1.

**Comment by jonathanolson** [comment]
Implemented, does that work well?

**Comment by kathy-phet** [comment]
After playing, I think jumps of 1 would be better for this slider.

**Comment by jonathanolson** [comment]
Rounding to 1 now.

**Comment by kathy-phet** [comment]
Looks great! Closing!

**Comment by phet-steele** [comment]
@kathy-phet do you mean that the slider will step from 8.00 m/s2 to 9.00 m/s2 in one sliding motion? I see two problems with this:

1. The tweakers step every 0.01 m/s2 (and they should stay this way). This makes it ***very*** hard to reach intermediate values, like 8.50 m/s2. Holding down the tweakers in this case to go from 8.00 -> 8.50 takes awhile, and tweakers would be the only way to reach this value. Think about it like this: 

The slider has a range of 0.00 to 25.00, allowing 2,500 different values to be obtained.
How many can be reached by sliding: 26
How many must be reached by tweaking: 2,474

That's 98.96% of values that can ONLY be reached with the tweakers. This sounds like ad incredibly annoying and poor UX. (Ignore if my math is a little off, the point still stands)

2. This slider is meant to be continuous, and rightly so. Increasing the step size to 1 m/s2 makes it feel more like a snapping slider since the slider would visually jump between values and not visit the intermediate values. Sliders like that would need tick marks (see the Friction slider directly below). This feels wrong to have tick marks AND tweakers for a slider.

**Comment by kathy-phet** [comment]
@phet-steele - 

Re #1. In thinking about teaching, the use case of getting to a particular value of gravity is less common than wanting to easily do experiments of doubling, etc.  The double digit readout is only because we want to show Earth at 9.81 with that precision, so when you use the drop down you get to that exactly. So I was weighing the ease of data taking at nice values over the duration it takes to get to a single value between the two you are at. It takes about 5 seconds to go .5 if you hold down the tweaker. (Now if you don't know to hold down the tweaker that can be annoying if you are going for something specific). 

Re #2. The mass and length sliders already work this way, so its consistent with those sliders. So I don't think it will be that confusing to the user. It also has more points (25) along it, so it feels pretty continuous -- more so than the other sliders for mass and length. They have their behavior for the same reason -- ease of doubling to nice numbers.

**Comment by phet-steele** [comment]
@kathy-phet I edited point 2 a bit before your reply to reflect that maybe the mass and length sliders could change too. Perhaps doubling up on ticks and tweakers would look fine for all of the mentioned sliders?

For point 1, I think that your reply still makes sense with a step size of 0.5 m/s2. I don't have a problem with that the step size, it's just that 1.0 feels excessively large and can make the sudden rounding unwieldy when starting to drag sliders.

**Comment by kathy-phet** [comment]
Let's chat on Monday when @arouinfar has had a chance to review. 

We made this change to sliders that have this smart sliding on purpose to help with reproducibility, but happy to revisit how it feels. I was finding the 0.5 jumps on the gravity slider made it harder to easily and quickly jump by a factor of 2. Just easier to think in whole number than having to process the 0.5 values as I slide. And with the 25 values it was already a lot of values along the length of the slider.

**Comment by arouinfar** [comment]
I realize that using a smooth slider track with a snappy thumb is a bit unorthodox, but I think it's important here. The snappy thumb is great for exploration and reproducibility, but it's still important to allow for more precise values to be set in this particular sim. 

@phet-steele let me take a look at the version with 0.5 m/s^2 steps since I'm only able to access the latest dev (0.1 m/s^2 steps) and master (1 m/s^2 steps). 

I prefer the version with 0.5 m/s^2 steps. I don't find that the 0.5 m/s^2 steps particularly difficult in doubling values in comparison to the 1 m/s^2 steps, and it cuts down the amount of time to set precise value by half, so I think it's a good compromise.

**Comment by arouinfar** [comment]
@jonathanolson my vote would be to revert the gravity step size to 0.5 m/s^2 steps.

**Comment by jonathanolson** [comment]
0.5 steps pushed to master.

**Comment by arouinfar** [comment]
Looks good to me @jonathanolson!
