### ISSUE TITLE
User feedback: line graph

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/pendulum-lab#192]
Graph needs to have line graphs to allow for better analysis of the entire motion.  Bar graphs are only good for unconnected snapshots of data.

**Comment by arouinfar** [comment]
@oliver-phet the bar graph was ported from the original Flash version, but cleaned up a bit to and given zoom in/out buttons. By design, the feedback is meant to be qualitative.

I think the user is asking for a graph like like the one in the full Energy Skate Park:

<img width="398" alt="screen shot 2017-09-14 at 10 55 07 am" src="https://user-images.githubusercontent.com/8419308/30442980-43d84dba-993b-11e7-8acb-d448ab576908.png">

This is definitely beyond the scope of Pendulum Lab. Perhaps Energy Skate Park would be a better choice to address this teacher's goals for the conservation of energy.

I don't agree that bar graphs are "only good for unconnected snapshots." The user could try using Pendulum Lab in slow motion, or pausing and stepping through the motion to see the graph evolve a bit more slowly.

**Comment by oliver-phet** [comment]
Reply to user sent. Closing.
