### ISSUE TITLE
Period Trace at Small Lengths

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#80]
The period trace is drawn strangely at lower lengths:

![pendla](https://cloud.githubusercontent.com/assets/5863899/7991853/811e3608-0ab8-11e5-9e8b-7d1c6d04e800.gif)

Tested on Win 8.1 FF

Troubleshooting information:
Name: Pendulum Lab
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.4/pendulum-lab_en.html
Version: 1.0.0-dev.4 2015-06-04 17:46:07 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"comment":"# pendulum-lab 1.0.0-dev.4 Thu Jun 04 2015 11:46:00 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"7de4a27be4b322b71c5f5046df193a03ccf0f161","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"c7d6ea5f9bef6e3882309af56ad409908dd28878","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"pendulum-lab":{"sha":"2b4cf70e4a8a88b37882b1643d44155a806508ab","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"c9087fbb0cdd83f79452330fec3b83f809e2c0d8","branch":"master"}}

**Comment by ariel-phet** [comment]
Hopefully will be addressed with new minimum length

**Comment by jonathanolson** [comment]
Is there a minimum length decided for the sim yet?

**Comment by ariel-phet** [comment]
@jonathanolson - you should discuss with @arouinfar. Basically we want to make the new "scale" of the sim be 1 m. So turn the 2 meter stick, into a 1 meter stick and choose minimum lengths and sizes of the mass (visual size of the mass) such that things work out nicely.

**Comment by jonathanolson** [comment]
@arouinfar, should I just experiment with tuning values until I get something that looks good, and then check with you?

**Comment by arouinfar** [comment]
That would be great, @jonathanolson.

@ariel-phet, I think we'd originally discussed leaving the 2m stick as is, but limiting the length of the pendulum to 1.5m. If we still have scaling issues at 1.5m, we can drop down to 1m. I think it's best to leave as much length as possible to see the square root behavior, as that was the original motivation for changing the minimum length from 0.5 m to 0.1 m.

The square root behavior is now more obvious when comparing current scaling in HTML5 (left) to the original Flash sim (right):
![image](https://cloud.githubusercontent.com/assets/8419308/11126650/2c00d1be-892d-11e5-972c-2a954fa3af53.png)

If the length is limited to 1.5 m (left), the functional relationship is still reasonably clear, but we start to lose that if limiting the length to 1.0 m (right).
![image](https://cloud.githubusercontent.com/assets/8419308/11126446/42adb158-892c-11e5-9a87-0c0f496dc697.png)

**Comment by arouinfar** [comment]
Assigning to @jonathanolson to experiment with the scale.

**Comment by jonathanolson** [comment]
Leaving the maximum length at 2m seems to work well graphically (for small angles), otherwise there's a lot of empty space between what feels like the "top" and "bottom". At 1.5m we're still overlapping control panels.

I committed a fix that will allow the period trace to look nice down to 0.1m. Can you comment on the "scaling" issues that having the 2.0m pendulum causes?

**Comment by arouinfar** [comment]
@jonathanolson The problem arises from the size of the masses. The largest mass needs to be small enough to attach to a 0.1m string. With the current mass scaling, here's what the largest mass/smallest length looks like:
![image](https://cloud.githubusercontent.com/assets/8419308/11517009/24fd3d82-9844-11e5-889c-443cf8937b6f.png)

Here's the smallest mass/smallest length combo:
![image](https://cloud.githubusercontent.com/assets/8419308/11517029/3e457c1e-9844-11e5-8239-8000193fb1a2.png)

At this scale, there's not really room for the mass to get much larger before it's too big for the string.

One solution would be to increase the length of the 0.1m string to accommodate larger masses. This creates problems at the upper end of the length scale, however, as the 2m string will no longer fit on screen. Instead, we could limit the length to 0.1m to 1.5m. The sizes of the masses will also need to be scaled down some so that the largest mass fits on the smallest string.

>At 1.5m we're still overlapping control panels.

I'm not that concerned with overlapping the control panels since they now can float outside of dev at wider aspect ratios.

**Comment by jonathanolson** [comment]
Rescaled various things, and redid lengths/sizes on the period trace to also compensate. Testing 1m scale, since it could be more easily physically tested, AND the densities are more realistic (almost that of water) instead of the 2m scale (similar to the lightest balsa woods).

Assigning to @ariel-phet for testing.

**Comment by arouinfar** [comment]
@jonathanolson @ariel-phet I think the new scaling looks great!

>AND the densities are more realistic (almost that of water) instead of the 2m scale (similar to the lightest balsa woods).

I hadn't given the densities any thought before, but now that @jonathanolson has pointed it out, I think we are better off sticking with a max length of 1m.

**Comment by arouinfar** [comment]
I've plotted period vs. length for the new scale in dev.6 (left) along with the original Flash version (right). Both graphs have the same step size (0.05 m). Unfortunately, I don't think the square root relationship is more obvious in dev.6 than in the original Flash version. One of the learning goals of this sim is for students to derive the functional relationship between the period and length.

![image](https://cloud.githubusercontent.com/assets/8419308/12040922/2926e6c8-ae2a-11e5-8834-a1fb06a85460.png)

If we make the minimum length 0.1 m instead of 0.15 m, the square root relationship becomes clearer. (Or at least it's clearly non-linear.) 
![image](https://cloud.githubusercontent.com/assets/8419308/12041250/df4c3424-ae2c-11e5-93a7-412d904913d8.png)

The size of the minimum length in dev.6 looks good. Could we instead label that 0.1 m, and make the string just a bit longer at 1.0 m? We have a little bit of vertical real estate that we can work with. I don't mind if the pendulums overlap the panels (especially since they can now float out of dev). I also don't think it'll be necessary to adjust the mass sizes, since this is a rather fine-tuned adjustment to the length.

Reassigning to @jonathanolson.

**Comment by jonathanolson** [comment]
The size of the minimum length in dev.6 looks good. Could we instead label that 0.1 m, and make the string just a bit longer at 1.0 m? We have a little bit of vertical real estate that we can work with.

To fit the dynamic range of 0.1m-1m, it's effectively the same as increasing our maximum range (0.15m-1.5m). That goes significantly off the page:
![screen shot 2015-12-30 at 12 01 19 am](https://cloud.githubusercontent.com/assets/480878/12046952/a7d32028-ae88-11e5-9e55-936a11dbd03d.png)

If this is an important goal, is it worth looking at different scales, e.g. have the default 0.15m-1m, but then support 1m-7m as a mode? This would allow construction of a continuous chart from 0.15m-7m which I presume would be way better than a very small increase to the equivalent of ~1.5m.

**Comment by arouinfar** [comment]
Thanks for putting this into perspective @jonathanolson.

> is it worth looking at different scales, e.g. have the default 0.15m-1m, but then support 1m-7m as a mode? This would allow construction of a continuous chart from 0.15m-7m

I like this idea, but if there is a 1-7m mode, wouldn't the masses have a scaling problem/unreasonable densities?

@ariel-phet could you take a look at the last few comments and chime in?

**Comment by ariel-phet** [comment]
@arouinfar lets discuss in person....this may be one of those times where we just don't get everything on our wish list. With the various constraints of the sim, we may have to give up a little on this particular learning goal.

I will say, the gravity adjustment allows enough dynamic range that a square root relationship should be able to be obvious from plotting a fixed length with different "g" values against period. That will be an inverse squareroot relationship obviously, and would be square root relationship if considering frequency. Maybe we satisfy the learning goal that way, especially by mentioning it in the teacher tips and possibly with an exemplar lesson?

**Comment by ariel-phet** [comment]
Closing
