### ISSUE TITLE
No cut off on zoom out of energy graph

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/pendulum-lab#92]
Test device: iPad2 

Operating System: iOS 8.3

Browser: Safari

Problem description: You can just keep zooming out on the energy graph until no data is viewable.
Steps to reproduce:

Severity: Minor

Screenshots: 
![image](https://cloud.githubusercontent.com/assets/12610678/8087855/93633f2e-0f5a-11e5-8bb3-ad1471008d61.png)

Troubleshooting information (do not edit):
Name: Pendulum Lab
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.4/pendulum-lab_en.html
Version: 1.0.0-dev.4 2015-06-04 17:46:07 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"comment":"# pendulum-lab 1.0.0-dev.4 Thu Jun 04 2015 11:46:00 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"7de4a27be4b322b71c5f5046df193a03ccf0f161","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"c7d6ea5f9bef6e3882309af56ad409908dd28878","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"pendulum-lab":{"sha":"2b4cf70e4a8a88b37882b1643d44155a806508ab","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"c9087fbb0cdd83f79452330fec3b83f809e2c0d8","branch":"master"}}

**Comment by ariel-phet** [comment]
@arouinfar - we could set a limit on zooming. (and grey out the appropriate button once the limit is reached). Thoughts?

**Comment by arouinfar** [comment]
Limiting the zooming poses some challenges due to the huge range in energies that can be displayed. The default scale works nicely in most cases, and doesn't generally require a ton of zooming to optimize the energy graph. However, when dealing with the extremes, it can take quite a few clicks to optimize the zoom. Here's some data from a few test cases:

* Maximum energy (~75 J): max gravity, max length, max mass, 179* displacement -- zoom out 12x from default to optimize
![image](https://cloud.githubusercontent.com/assets/8419308/12040699/7dbb39de-ae28-11e5-87bb-f8f8bb3203d9.png)

* Minimum energy (~23 nJ): 0.01 m/s^2, min length, min mass, 1* displacement -- zoom in 55x from default for hairline bars (left), ~70x to look reasonable (middle), 75x to max out (right)

![image](https://cloud.githubusercontent.com/assets/8419308/12026123/1bb85826-ad73-11e5-8d96-720dd6c75b28.png) ![image](https://cloud.githubusercontent.com/assets/8419308/12026126/353fb62c-ad73-11e5-80b5-e4c75e224745.png)![image](https://cloud.githubusercontent.com/assets/8419308/12040530/04e6d398-ae27-11e5-9bf7-206680e76f03.png)


* A more realistic minimum (~4 mJ): Moon, min length, min mass, 10* displacement -- zoom in 16x from default to get hairline bars (left), 30x to look reasonable (middle), 35x to max out (right)

![image](https://cloud.githubusercontent.com/assets/8419308/12026072/94881f3a-ad72-11e5-8049-94975ab90dd5.png) ![image](https://cloud.githubusercontent.com/assets/8419308/12026063/7fb7c1a0-ad72-11e5-86d9-71e9f0813764.png)![image](https://cloud.githubusercontent.com/assets/8419308/12040477/88d8c860-ae26-11e5-9704-b9e18f73b3f1.png)

Based on this data, I would recommend we allow users to zoom out 12x and zoom in <i>at least</i> 35x from the default scale. Once the limit is reached, the appropriate button should be grayed out as to look inactive. Does this sound reasonable to you @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar perhaps it is then best to just set no limits? Trust the user to do what they need to do and assume that if they are pressing the zoom button multiple times they will not be surprised if things are out of range?

**Comment by arouinfar** [comment]
@ariel-phet that seems reasonable, given the range. I'll go ahead and close this issue. We can reopen it if there are any issues that crop up in interviews.
