### ISSUE TITLE
Add a second angle to be displayed when moving pendulum 2

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#95]
On touch devices, the user can grab both pendulums and move them at the same time. The angle that is displayed then struggles to show the angle of each pendulum and ends up flashing quickly between the two values. It would be helpful to add a second angle value display (maybe also make the text red to match the red color of the second pendulum) so that each angle can be seen separately.

**Comment by ariel-phet** [comment]
Thanks for the suggestion @phet-steele - assigning to @arouinfar for discussion

**Comment by arouinfar** [comment]
Great suggestion @phet-steele!

I think the best approach would be to add a readout for the second pendulum to the right of the midline. Currently, the angle readout always appears to the left of the midline (regardless of the direction of the displacement).

Here's a mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/11541476/af7e03d2-98ef-11e5-8ac4-5a5b9bd48b96.png)

Note that both angle readouts would only appear if both pendulums are simultaneously displaced. At times, the angle readout and pendulum will be on opposite sides of the midline. I think this is something we can live with, as it could get quite complicated to address. (For example, what happens if both pendulums are being dragged to the right? Would the smaller displacement always be shown on the left? What happens if one pendulum surpasses the other? Would the readouts swap?)

Assigning to @jonathanolson to add a separate readout for the second pendulum, as mocked up above.

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks. I considered moving the angles farther away from the center horizontally, so they're a bit easier to read while moving pendulums at most angles. Thoughts?

**Comment by arouinfar** [comment]
Looking good @jonathanolson! 

> I considered moving the angles farther away from the center horizontally, so they're a bit easier to read while moving pendulums at most angles. Thoughts?

I agree, let's give it a try.

**Comment by jonathanolson** [comment]
Moved them farther away, let me know if that looks good.

**Comment by arouinfar** [comment]
Looks great! Closing.
